# Generated by Django 3.0.1 on 2019-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('h', models.IntegerField(default=150)),
                ('w', models.IntegerField(default=50)),
            ],
        ),
    ]
